name = "DecompUtil"
uuid = "a6e39b05-4154-4474-92cb-6e6881149f60"
authors = ["Devansh Ramgopal Agrawal <devansh@umich.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
